CREATE TABLE "books" (
	"id" serial PRIMARY KEY NOT NULL,
	"title" text NOT NULL,
	"slug" text NOT NULL,
	"thumbnail" text,
	"description" text NOT NULL,
	"book_comments" text,
	"price" integer NOT NULL,
	"ISBN" text NOT NULL,
	"edition_no" integer NOT NULL,
	"state" text NOT NULL,
	"page_count" integer NOT NULL,
	"publish_time" timestamp NOT NULL,
	"is_active" boolean DEFAULT true NOT NULL,
	"created_by" serial NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"modified_by" integer,
	"modified_at" timestamp DEFAULT now(),
	CONSTRAINT "books_slug_unique" UNIQUE("slug"),
	CONSTRAINT "books_ISBN_unique" UNIQUE("ISBN")
);
