import "./globals.css";
import { QueryProvider } from "@/providers/query-provider";
import { Toaster } from "@/components/ui/sonner";
import { AppProvider } from "@/providers/Appcontext";
import { ReactQueryDevtools } from "@tanstack/react-query-devtools";

import localFont from "next/font/local";
const font = localFont({
  src: [
    {
      path: "../public/static/fonts/fontiran/fonts/IranSans/woff2/IRANSansWeb.woff2",
      style: "normal",
      weight: "normal",
    },
    {
      path: "../public/static/fonts/fontiran/fonts/IranSans/woff2/IRANSansWeb_Black.woff2",
      style: "normal",
      weight: "900",
    },
    {
      path: "../public/static/fonts/fontiran/fonts/IranSans/woff2/IRANSansWeb_Bold.woff2",
      style: "normal",
      weight: "bold",
    },
    {
      path: "../public/static/fonts/fontiran/fonts/IranSans/woff2/IRANSansWeb_Medium.woff2",
      style: "normal",
      weight: "500",
    },
    {
      path: "../public/static/fonts/fontiran/fonts/IranSans/woff2/IRANSansWeb_Light.woff2",
      style: "normal",
      weight: "300",
    },
    {
      path: "../public/static/fonts/fontiran/fonts/IranSans/woff2/IRANSansWeb_UltraLight.woff2",
      style: "normal",
      weight: "200",
    },
  ],
});

import type { Metadata } from "next";
export const metadata: Metadata = {
  title: "iamss project",
  description: "Generated by ROBIN",
  icons: {
    icon: "/static/images/logo.png",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={font.className}>
        <AppProvider>
          <QueryProvider>
            <Toaster dir="rtl" position="top-center"/>
            {children}
            {/* <ReactQueryDevtools initialIsOpen={true} /> */}
          </QueryProvider>
        </AppProvider>
      </body>
    </html>
  );
}
